import Head from "next/head";
import HomeCompIndex from "@/components/home";

export default function Home() {
  return (
    <>
      <Head>
        <title>Social App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main>
        <HomeCompIndex />
      </main>
    </>
  );
}
